[project]
drom-version = "0.1"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@ocamlpro.com>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "OCamlPro SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.10.0"
name = "ocamlup"
skeleton = "program"
synopsis = "The ocamlup project"
version = "0.1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """This is the description
of the ocamlup OCaml project
"""

[project]
skip = []

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
makefile-trailer = """
WEBSITE_NAME:=ft
WEBSITE_DIR:=/var/www/ocamlup.ocaml-lang.org/www
ARCHITECTURE:=x86_64-unknown-linux-gnu
OPAMBIN_STORE:=$(HOME)/.opam/plugins/opam-bin/store
-include Makefile.config
rsync:
\tscp ocamlup $(WEBSITE_NAME):$(WEBSITE_DIR)/dist/$(ARCHITECTURE)/ocamlup-init
\tscp scripts/ocamlup-shell.sh $(WEBSITE_NAME):$(WEBSITE_DIR)/ocamlup-shell.sh

rsync-bin:
\trsync -auv $(OPAMBIN_STORE)/archives/. ft:/var/www/ocamlup.ocaml-lang.org/www/dist/$(ARCHITECTURE)/archives/.
\trsync -auv $(OPAMBIN_STORE)repo/packages/. ft:/var/www/ocamlup.ocaml-lang.org/www/dist/$(ARCHITECTURE)/repo/packages/.
\tssh ft rm -rf '$(WEBSITE_DIR)/dist/$(ARCHITECTURE)/repo/packages/*+bin'
"""
dot-gitignore-trailer = """
/drom
/ocamlup.hash
"""

[[package]]
dir = "src/ocamlup"
# edit 'src/ocamlup/package.toml' for package-specific options

[[package]]
dir = "src/ocamlup_lib"
# edit 'src/ocamlup_lib/package.toml' for package-specific options

[[package]]
dir = "src/opam_bin_lib"
# edit 'src/ocamlup_lib/package.toml' for package-specific options

[[package]]
dir = "src/drom_lib"
# edit 'src/ocamlup_lib/package.toml' for package-specific options

[[package]]
dir = "src/drom_toml"
# edit 'src/ocamlup_lib/package.toml' for package-specific options

